import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { toolResponse } from "./operation-result.ts";
import { TaskPlanService, type TaskPlanSessionState } from "./operations.ts";
import { PlanAbandonParameters, PlanAdvanceParameters, PlanBindTaskParameters, PlanGetParameters, PlanReportTaskResultParameters, PlanReviewParameters, PlanSetTaskStatusParameters, PlanStartParameters, PlanSubmitSectionParameters } from "./schemas.ts";

export function registerTaskPlanTools(pi: ExtensionAPI, state: TaskPlanSessionState): void {
  pi.registerTool({ name: "plan_start", label: "Start Harness Plan", description: "Create a new one-file Pi Plan Harness markdown skeleton. Does not call a model or submit drafted content.", promptSnippet: "Start a new one-file Harness Plan when the user wants structured planning before execution. When starting from a long natural-language brief, summarize a concise title first and pass it as title so the filename stays short.", parameters: PlanStartParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_start aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).start(params.goal, params.title)); } });
  pi.registerTool({ name: "plan_get", label: "Get Harness Plan", description: "Read and reconcile the current Harness Plan, returning sections, metadata, and document_hash.", promptSnippet: "Read the current Harness Plan snapshot and document_hash.", parameters: PlanGetParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_get aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).get(params.planPath)); } });
  pi.registerTool({ name: "plan_status", label: "Harness Plan Status", description: "Read and reconcile the current Harness Plan and return the Human-facing lifecycle status.", promptSnippet: "Check current Harness Plan stage and next step.", parameters: PlanGetParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_status aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).status(params.planPath)); } });
  pi.registerTool({ name: "plan_submit_section", label: "Submit Harness Plan Section", description: "Submit content for the section implied by the effective stage. Requires expected_document_hash and rejects stale writes.", promptSnippet: "Submit the current stage section through Harness validation instead of editing the plan file directly.", parameters: PlanSubmitSectionParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_submit_section aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).submitSection(params)); } });
  pi.registerTool({ name: "plan_advance", label: "Advance Harness Plan", description: "Apply a Human gate: approve What/Why, approve Plan, authorize executing, roll next round, or complete with constraints. If this advances into plan or tasks drafting, continue immediately by drafting and submitting that next section before the final user-facing reply.", promptSnippet: "Advance only when Human approval intent is clear; if the result stage is plan or tasks, immediately draft and submit that next section before replying.", promptGuidelines: ["After plan_advance returns an applied result whose snapshot stage is plan or tasks, do not stop with a stage-change summary. Immediately draft the new current section, call plan_submit_section, show the generated content, file path, edit options, and the next approval step."], parameters: PlanAdvanceParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_advance aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).advance(params)); } });
  pi.registerTool({ name: "plan_review", label: "Review Harness Plan", description: "Review current stage. what_why/plan deterministic only; tasks may atomically submit candidate_tasks and current-round review summary.", promptSnippet: "Review the current Harness Plan stage; use candidate_tasks only for Tasks review.", parameters: PlanReviewParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_review aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).review(params)); } });
  pi.registerTool({ name: "plan_bind_task", label: "Bind Harness Task", description: "Bind one open current-round Task in executing stage and return its frozen contract. Does not execute or schedule work.", promptSnippet: "Bind a current-round Task before executing it for the Human.", parameters: PlanBindTaskParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_bind_task aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).bindTask(params)); } });
  pi.registerTool({ name: "plan_report_task_result", label: "Report Harness Task Result", description: "Report in_progress, blocked, or completed for the current task binding. Completed requires every Acceptance item satisfied.", promptSnippet: "Report the result of a bound Harness Task before ending the execution turn.", parameters: PlanReportTaskResultParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_report_task_result aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).reportTaskResult(params)); } });
  pi.registerTool({ name: "plan_set_task_status", label: "Set Harness Task Status", description: "Apply an explicit Human instruction to mark a current-round Task completed or open. Only changes Completion plus deterministic stage progress.", promptSnippet: "Use plan_set_task_status only for explicit Human task done/open instructions.", parameters: PlanSetTaskStatusParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_set_task_status aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).setTaskStatus(params)); } });
  pi.registerTool({ name: "plan_abandon", label: "Abandon Harness Plan", description: "Close an unfinished Harness Plan as abandoned with an explicit Human reason. Does not delete files.", promptSnippet: "Abandon the current Harness Plan only after explicit Human abandon intent.", parameters: PlanAbandonParameters, executionMode: "sequential", async execute(_id, params, signal, _u, ctx) { if (signal?.aborted) throw new Error("plan_abandon aborted"); return toolResponse(await new TaskPlanService(ctx.cwd, state).abandon(params)); } });
}
