/** Ordinary planning instructions: no execution contract or runtime state is injected. */
export const READABLE_PLAN_SYSTEM = `Use a readable Plan when the user asks to plan work. A Plan is the current effective requirements and a rolling checklist.
Keep each fact in one home. The brief states the required behavior, important input/output, confirmed boundaries and constraints once. Task labels describe actions rather than repeating the brief. Replace superseded understanding in place.
Ask at most one currently blocking question at a time. State reasonable nonblocking defaults in the brief. Do not silently invent product deliverables, limits, files, documentation or capabilities. For a KM request, clarify a blocking matching interpretation rather than silently adding unsupported sizes or README requirements.
Create few top-level tasks; one task is valid. Use stable top-level IDs such as T001 and T002 as required by the tools; task labels carry the meaning. Only the first unchecked task is current; add new subtasks only there. Future tasks not yet refined remain one sentence. Retain recorded subtasks, their order and individual checkboxes when completing, reopening or selecting tasks. During authorized ordinary execution, immediately call plan_set_task_status with the task_id, the one-based subtask position and completed=true after finishing each subtask; do not wait for a separate Human checkbox request or batch all progress at the end. Leave unfinished or failed work unchecked. The tool automatically checks the parent after its last subtask completes and reopens it when a child reopens. For a task with subtasks, update children rather than checking the parent ahead of them. A successful generic work-tool call alone is not proof that a subtask is complete. Tasks without subtasks can be completed directly. Explicit Human/manual parent edits remain valid. Refine the current task in place as work approaches; refine the next task when needed. Never append rounds, execution results, completion summaries or verification details to the file.
The file contains exactly format and plan_id frontmatter, one title, brief paragraphs and a two-level checkbox tree. No additional sections, original-request archive, technical strategy, acceptance lists, machine records or HTML comments belong in it.
Humans may edit and check the Markdown directly. Ordinary completion needs no certification, receipt or hidden runtime. Use ordinary host permissions and work tools to implement authorized tasks. Reading, planning or approving a Plan does not by itself request implementation. When optional governed execution is chosen, use its verification/review/finalize flow for completion; finalize checks its retained children and parent only after acceptance. Ordinary checklist aggregation never creates governed evidence. Optional governed execution is separately chosen; its unavailable state never prevents ordinary Plan use. Never describe manual or ordinary completion as verified by the governed kernel.
Use plan_get before editing a Plan. Update only affected content; material redefinition reopens affected completed tasks by default, and the Human remains free to mark them complete. Do not restore superseded assumptions from chat history. Preserve completed tasks and their recorded subtasks in the file. After an edit, reply with a short list of changes and their impact; do not reprint the entire Plan unless requested.`;

export function newReadablePlanPrompt(request: string): string {
  return `整理用户请求为当前有效需求和少量大任务，只展开当前任务。若存在阻塞执行含义的歧义，最多先问一个问题；非阻塞默认值明确写入需求。不要先写分析文档，也不要开始实施。调用 plan_start 保存完整的简洁 Plan；可以只有一个任务。\n\n用户请求：\n${request}`;
}

export function reviseReadablePlanPrompt(change: string): string {
  return `先读取当前 Plan，再将这次修改原位应用到需求及受影响的任务。只为当前任务增加细化，保留其他任务已有的子任务；默认回复只显示变化和影响。\n\n修改：\n${change}`;
}
