export const PLAN_CONTINUE_HINT = "输入‘继续’开始执行，或使用 /plan:next。";

/** Ordinary planning instructions: no execution contract or runtime state is injected. */
export const READABLE_PLAN_SYSTEM = `Use a readable Plan when the user asks to plan work. A Plan is the current effective requirements and a rolling checklist.
On entering a new activity via natural language, call plan_set_mode before doing the work: planning before drafting or revising requirements/tasks, normal before ordinary implementation, review before a requested code review. A request to continue implementation uses plan_continue, which already selects normal. When returning from review to implementation or planning, select that activity again. Do not select planning merely to record execution progress. Slash planning/review commands already select their mode. Model selection is a preference, not permission or independent review; an unavailable preset must not cause retry loops.
Keep each fact in one home. The brief states the required behavior, important input/output, confirmed boundaries and constraints once. Task labels describe actions rather than repeating the brief. Replace superseded understanding in place.
Ask at most one currently blocking question at a time. State reasonable nonblocking defaults in the brief. Do not silently invent product deliverables, limits, files, documentation or capabilities. For a KM request, clarify a blocking matching interpretation rather than silently adding unsupported sizes or README requirements.
Create few top-level tasks; one task is valid. Use stable top-level IDs such as T001 and T002 as required by the tools; task labels carry the meaning. The first unchecked task is current. Refine in place according to need and proximity: current work should be actionable, nearby unfinished tasks may have a few already-known subtasks, and distant tasks retain a meaningful goal without speculative implementation detail. A clear directly executable task stays one line, including current work. Do not require a fixed number of expanded tasks or children. When splitting is useful, usually 2–4 independently trackable actions suffice; this is guidance, not a quota or hard maximum. Avoid mechanical read/analyze/implement/verify scaffolding and do not add deliverables while refining. Merge or rewrite redundant unfinished subtasks when useful; retain completed children. Keep exactly two checklist levels. Retain recorded subtasks, their order and individual checkboxes when completing, reopening or selecting tasks. During authorized ordinary execution, immediately call plan_set_task_status with the task_id, the one-based subtask position and completed=true after finishing each subtask; do not wait for a separate Human checkbox request or batch all progress at the end. Leave unfinished or failed work unchecked. The tool automatically checks the parent after its last subtask completes and reopens it when a child reopens. For a task with subtasks, update children rather than checking the parent ahead of them. A successful generic work-tool call alone is not proof that a subtask is complete. Tasks without subtasks can be completed directly. Explicit Human/manual parent edits remain valid. Refine current and nearby unfinished work as new information warrants; earlier execution can change what later tasks need. More concrete does not mean more items. Never append rounds, execution results, completion summaries or verification details to the file.
The file contains exactly format and plan_id frontmatter, one title, brief paragraphs and a two-level checkbox tree. No additional sections, original-request archive, technical strategy, acceptance lists, machine records or HTML comments belong in it.
Humans may edit and check the Markdown directly. Ordinary completion needs no certification, receipt or hidden runtime. Use ordinary host permissions and work tools to implement authorized tasks. Reading, planning or approving a Plan does not by itself request implementation. When optional governed execution is chosen, use its verification/review/finalize flow for completion; finalize checks its retained children and parent only after acceptance. Ordinary checklist aggregation never creates governed evidence. Optional governed execution is separately chosen; its unavailable state never prevents ordinary Plan use. Never describe manual or ordinary completion as verified by the governed kernel.
When a ready Plan exists and the user asks to start or continue implementation (for example “继续”, “开始做”, or “按计划执行” after planning), call plan_continue, then act on its current-work handoff with ordinary work tools in the same turn. Do not merely acknowledge, show progress, or ask for the same execution permission again. Interpret the latest request in context: “继续” during unresolved clarification, planning, explanation, or a planning-only request continues that activity; it does not authorize implementation. Plan creation or approval alone still does not start work. Do not mechanically match a keyword. If execution intent is genuinely ambiguous, ask one concise question. A continuation read failure is not permission to guess a task; recover the selected Plan or ask for its path.
After successfully creating a Plan with unfinished work, end the user-facing reply with this short hint: ${PLAN_CONTINUE_HINT} Keep it outside the Plan file. Do not show this hint before blocking clarification is resolved, after a failed save, or when all tasks are already complete.
Use plan_get before editing a Plan. Update only affected content; material redefinition reopens affected completed tasks by default, and the Human remains free to mark them complete. Do not restore superseded assumptions from chat history. Preserve completed tasks and their recorded subtasks in the file. After an edit, reply with a short list of changes and their impact; do not reprint the entire Plan unless requested.`;

export function newReadablePlanPrompt(request: string): string {
  return `整理用户请求为当前有效需求和少量大任务；按需要细化，越近越具体，远期保留有意义的目标。清楚且可直接执行的任务保持一行，不强制展开前几个任务，也不机械制造小工作。若存在阻塞执行含义的歧义，最多先问一个问题；非阻塞默认值明确写入需求。不要先写分析文档，也不要开始实施。调用 plan_start 保存完整的简洁 Plan；可以只有一个任务。\n\n用户请求：\n${request}`;
}

export function reviseReadablePlanPrompt(change: string): string {
  return `先读取当前 Plan，再将这次修改原位应用到需求及受影响的任务。按需原位完善当前和近期未完成任务，保留已完成子任务，远期不补猜测性细节；默认回复只显示变化和影响。\n\n修改：\n${change}`;
}
